export default {
    INCREMENT : 'INCREMENT',
    DECREMENT: 'DECREMENT',
    START_MAIN_LOADER: 'START_MAIN_LOADER',
    STOP_MAIN_LOADER: 'STOP_MAIN_LOADER',
    SET_LOGIN_USER_INFO:'SET_LOGIN_USER_INFO',
    CLEAR_LOGIN_USER: 'CLEAR_LOGIN_USER',
    AUTH_STATE_IN:'AUTH_STATE_IN',
    AUTH_STATE_OUT:'AUTH_STATE_OUT',    
    GET_ALL_USER:'GET_ALL_USER',
    GET_CHAT_MESSAGES: 'GET_CHAT_MESSAGES',
    CLEAR_CHAT_MESSAGES: 'CLEAR_CHAT_MESSAGES',
    GET_ALL_CONVERSATIONS:'GET_ALL_CONVERSATIONS',
}